import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  interviewSidebar: [
    'intro',
    {
      type: 'category',
      label: 'JavaScript 基础',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'javascript'},
      ],
    },
    {
      type: 'category',
      label: 'TypeScript',
      items: [
        {type: 'autogenerated', dirName: 'typescript'},
      ],
    },
    {
      type: 'category',
      label: 'React',
      items: [
        {type: 'autogenerated', dirName: 'react'},
      ],
    },
    {
      type: 'category',
      label: 'Vue',
      items: [
        {type: 'autogenerated', dirName: 'vue'},
      ],
    },
    {
      type: 'category',
      label: 'AI 应用开发',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'ai'},
      ],
    },
    {
      type: 'category',
      label: '工程化',
      items: [
        {type: 'autogenerated', dirName: 'engineering'},
      ],
    },
    {
      type: 'category',
      label: '前端性能优化',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'performance'},
      ],
    },
  ],
};

export default sidebars;
