import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  interviewSidebar: [
    'intro',
    {
      type: 'category',
      label: 'JavaScript 基础',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'javascript'}],
    },
    {
      type: 'category',
      label: 'TypeScript',
      items: [{type: 'autogenerated', dirName: 'typescript'}],
    },
    {
      type: 'category',
      label: 'React',
      items: [{type: 'autogenerated', dirName: 'react'}],
    },
    {
      type: 'category',
      label: 'Vue',
      items: [{type: 'autogenerated', dirName: 'vue'}],
    },
    {
      type: 'category',
      label: 'AI 应用开发',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'ai'}],
    },
    {
      type: 'category',
      label: 'Agent 开发实战',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'agent-development'}],
    },
    {
      type: 'category',
      label: 'CSS',
      items: [{type: 'autogenerated', dirName: 'css'}],
    },
    {
      type: 'category',
      label: '浏览器原理',
      items: [{type: 'autogenerated', dirName: 'browser'}],
    },
    {
      type: 'category',
      label: '计算机网络',
      items: [{type: 'autogenerated', dirName: 'network'}],
    },
    {
      type: 'category',
      label: '工程化',
      items: [{type: 'autogenerated', dirName: 'engineering'}],
    },
    {
      type: 'category',
      label: '数据结构与算法',
      items: [{type: 'autogenerated', dirName: 'algorithms'}],
    },
    {
      type: 'category',
      label: '计算机基础',
      items: [{type: 'autogenerated', dirName: 'computer-basics'}],
    },
    {
      type: 'category',
      label: '前端性能优化',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'performance'}],
    },
    {
      type: 'category',
      label: '公务员面试',
      items: [{type: 'autogenerated', dirName: 'civil-service'}],
    },
    {
      type: 'category',
      label: '设计模式',
      items: [{type: 'autogenerated', dirName: 'design-patterns'}],
    },
    {
      type: 'category',
      label: '小程序开发实战',
      items: [{type: 'autogenerated', dirName: 'miniapp'}],
    },
    {
      type: 'category',
      label: '前端监控与异常处理',
      items: [{type: 'autogenerated', dirName: 'monitoring'}],
    },
    {
      type: 'category',
      label: '微前端架构',
      items: [{type: 'autogenerated', dirName: 'micro-frontend'}],
    },
    {
      type: 'category',
      label: '跨端开发',
      items: [{type: 'autogenerated', dirName: 'cross-platform'}],
    },
    {
      type: 'category',
      label: 'Node.js 与 SSR',
      items: [{type: 'autogenerated', dirName: 'nodejs'}],
    },
    {
      type: 'category',
      label: '前端可视化',
      items: [{type: 'autogenerated', dirName: 'visualization'}],
    },
    {
      type: 'category',
      label: 'WebAssembly',
      items: [{type: 'autogenerated', dirName: 'wasm'}],
    },
    {
      type: 'category',
      label: '低代码平台',
      items: [{type: 'autogenerated', dirName: 'lowcode'}],
    },
    {
      type: 'category',
      label: '无障碍访问 (A11y)',
      items: [{type: 'autogenerated', dirName: 'accessibility'}],
    },
    {
      type: 'category',
      label: '国际化 (i18n)',
      items: [{type: 'autogenerated', dirName: 'i18n'}],
    },
    {
      type: 'category',
      label: 'SEO 优化',
      items: [{type: 'autogenerated', dirName: 'seo'}],
    },
    {
      type: 'category',
      label: 'Serverless 与边缘计算',
      items: [{type: 'autogenerated', dirName: 'serverless'}],
    },
    {
      type: 'category',
      label: '前端架构设计',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: '测试与质量保障',
      items: [{type: 'autogenerated', dirName: 'testing'}],
    },
    {
      type: 'category',
      label: '调试与排错',
      items: [{type: 'autogenerated', dirName: 'debugging'}],
    },
    {
      type: 'category',
      label: 'TypeScript 进阶',
      items: [{type: 'autogenerated', dirName: 'typescript-advanced'}],
    },
    {
      type: 'category',
      label: 'JavaScript 模块化',
      items: [{type: 'autogenerated', dirName: 'javascript-modules'}],
    },
    {
      type: 'category',
      label: 'CSS 架构',
      items: [{type: 'autogenerated', dirName: 'css-architecture'}],
    },
    {
      type: 'category',
      label: 'React 进阶',
      items: [{type: 'autogenerated', dirName: 'react-advanced'}],
    },
    {
      type: 'category',
      label: 'Vue 进阶',
      items: [{type: 'autogenerated', dirName: 'vue-advanced'}],
    },
    {
      type: 'category',
      label: '状态机',
      items: [{type: 'autogenerated', dirName: 'state-machine'}],
    },
    {
      type: 'category',
      label: 'WebSocket 深入',
      items: [{type: 'autogenerated', dirName: 'websocket-advanced'}],
    },
    {
      type: 'category',
      label: '浏览器 API',
      items: [{type: 'autogenerated', dirName: 'browser-api'}],
    },
    {
      type: 'category',
      label: '现代 API 方案',
      items: [{type: 'autogenerated', dirName: 'api-advanced'}],
    },
    {
      type: 'category',
      label: 'WebGL 与 3D',
      items: [{type: 'autogenerated', dirName: 'webgl'}],
    },
    {
      type: 'category',
      label: 'Canvas 游戏开发',
      items: [{type: 'autogenerated', dirName: 'canvas-game'}],
    },
    {
      type: 'category',
      label: 'PWA 实战',
      items: [{type: 'autogenerated', dirName: 'pwa'}],
    },
    {
      type: 'category',
      label: 'Electron 桌面开发',
      items: [{type: 'autogenerated', dirName: 'electron'}],
    },
    {
      type: 'category',
      label: 'Monorepo 进阶',
      items: [{type: 'autogenerated', dirName: 'monorepo'}],
    },
    {
      type: 'category',
      label: '工程化进阶',
      items: [{type: 'autogenerated', dirName: 'engineering-advanced'}],
    },
    {
      type: 'category',
      label: '移动端适配',
      items: [{type: 'autogenerated', dirName: 'mobile'}],
    },
    {
      type: 'category',
      label: '面试软技能',
      items: [{type: 'autogenerated', dirName: 'interview-soft'}],
    },
    {
      type: 'category',
      label: '手写题',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'handwrite'}],
    },
  ],
};

export default sidebars;
