import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  interviewSidebar: [
    'intro',
    {
      type: 'category',
      label: 'JavaScript 基础',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'javascript'},
      ],
    },
    {
      type: 'category',
      label: 'TypeScript',
      items: [
        {type: 'autogenerated', dirName: 'typescript'},
      ],
    },
    {
      type: 'category',
      label: 'React',
      items: [
        {type: 'autogenerated', dirName: 'react'},
      ],
    },
    {
      type: 'category',
      label: 'Vue',
      items: [
        {type: 'autogenerated', dirName: 'vue'},
      ],
    },
    {
      type: 'category',
      label: 'AI 应用开发',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'ai'},
      ],
    },
    {
      type: 'category',
      label: 'CSS',
      items: [
        {type: 'autogenerated', dirName: 'css'},
      ],
    },
    {
      type: 'category',
      label: '浏览器原理',
      items: [
        {type: 'autogenerated', dirName: 'browser'},
      ],
    },
    {
      type: 'category',
      label: '计算机网络',
      items: [
        {type: 'autogenerated', dirName: 'network'},
      ],
    },
    {
      type: 'category',
      label: '工程化',
      items: [
        {type: 'autogenerated', dirName: 'engineering'},
      ],
    },
    {
      type: 'category',
      label: '数据结构与算法',
      items: [
        {type: 'autogenerated', dirName: 'algorithms'},
      ],
    },
    {
      type: 'category',
      label: '计算机基础',
      items: [
        {type: 'autogenerated', dirName: 'computer-basics'},
      ],
    },
    {
      type: 'category',
      label: '前端性能优化',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'performance'},
      ],
    },
    {
      type: 'category',
      label: '设计模式',
      items: [
        {type: 'autogenerated', dirName: 'design-patterns'},
      ],
    },
    {
      type: 'category',
      label: '小程序开发实战',
      items: [
        {type: 'autogenerated', dirName: 'miniapp'},
      ],
    },
    {
      type: 'category',
      label: '手写题',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: 'handwrite'},
      ],
    },
  ],
};

export default sidebars;
